export type CatalogBrand = {
  name: string;
  officialName: string;
  slug: string;
  image: string;
  iconicModel: string;
  officialUrl: string;
  models: readonly string[];
};

export const CATALOG_REVIEWED_AT = "август 2026";

export const CATALOG_BRANDS: readonly CatalogBrand[] = [
  {
    name: "0mega",
    officialName: "OMEGA",
    slug: "0mega",
    image: "/iconic-watches/omega.webp",
    iconicModel: "Speedmaster Moonwatch Professional",
    officialUrl: "https://www.omegawatches.com/watches",
    models: ["Speedmaster", "Seamaster Diver 300M", "Seamaster Aqua Terra 150M", "Seamaster Planet Ocean 600M", "Seamaster 300", "Constellation", "De Ville Prestige", "De Ville Trésor", "Specialities"],
  },
  {
    name: "Audemars Piguet",
    officialName: "Audemars Piguet",
    slug: "audemars-piguet",
    image: "/iconic-watches/audemars-piguet.webp",
    iconicModel: "Royal Oak “Jumbo” Extra-Thin",
    officialUrl: "https://www.audemarspiguet.com/en/collections",
    models: ["Code 11.59 by Audemars Piguet", "Royal Oak", "Royal Oak Offshore", "Royal Oak Concept", "Neo Frame", "Établisseurs"],
  },
  {
    name: "Bell Ross",
    officialName: "Bell & Ross",
    slug: "bell-ross",
    image: "/iconic-watches/bell-ross.webp",
    iconicModel: "BR-03 Black Matte",
    officialUrl: "https://bellross.com/en-us/collections/toutes-nos-montres",
    models: ["BR-03", "BR-03 Diver", "BR-03 Chrono", "BR-X3", "BR-05", "BR-X5", "Vintage", "Flight Instruments", "BR 03 Cyber"],
  },
  {
    name: "Blancpain",
    officialName: "Blancpain",
    slug: "blancpain",
    image: "/iconic-watches/blancpain.webp",
    iconicModel: "Fifty Fathoms Automatique",
    officialUrl: "https://www.blancpain.com/en/collections",
    models: ["Villeret", "Ladybird", "Fifty Fathoms", "Air Command", "Métiers d’Art"],
  },
  {
    name: "Breitling",
    officialName: "Breitling",
    slug: "breitling",
    image: "/iconic-watches/breitling.webp",
    iconicModel: "Navitimer B01 Chronograph",
    officialUrl: "https://www.breitling.com/us-en/watches/",
    models: ["Navitimer", "Chronomat", "Superocean Heritage", "Avenger", "Classic AVI", "Premier", "Top Time", "Superocean", "Professional"],
  },
  {
    name: "BVLGARI",
    officialName: "Bvlgari",
    slug: "bvlgari",
    image: "/iconic-watches/bvlgari.webp",
    iconicModel: "Octo Finissimo Automatic",
    officialUrl: "https://www.bulgari.com/en-us/watches",
    models: ["Octo", "Serpenti", "Bvlgari Bvlgari", "Lvcea", "Divas’ Dream", "Aluminium", "High-End Watches"],
  },
  {
    name: "Cartier",
    officialName: "Cartier",
    slug: "cartier",
    image: "/iconic-watches/cartier.webp",
    iconicModel: "Santos de Cartier",
    officialUrl: "https://www.cartier.com/en-us/watches/collections/",
    models: ["Santos de Cartier", "Santos-Dumont", "Tank", "Panthère de Cartier", "Ballon Bleu de Cartier", "Baignoire", "Pasha de Cartier", "Ronde de Cartier", "Coussin de Cartier", "Cartier Privé", "Tortue"],
  },
  {
    name: "Chanel",
    officialName: "CHANEL",
    slug: "chanel",
    image: "/iconic-watches/chanel.webp",
    iconicModel: "J12 Caliber 12.1",
    officialUrl: "https://www.chanel.com/us/watches/collection/c/4x2/",
    models: ["J12", "Première", "BOY·FRIEND", "CODE COCO", "MONSIEUR"],
  },
  {
    name: "DIOR",
    officialName: "Dior",
    slug: "dior",
    image: "/iconic-watches/dior.webp",
    iconicModel: "Chiffre Rouge Chronographe",
    officialUrl: "https://www.dior.com/en_us/fashion/jewelry-timepieces/timepieces-by-collection/all-pieces",
    models: ["La D de Dior", "La D My Dior", "La Mini D My Dior", "La D de Dior Satine", "Gem Dior", "Dior Grand Bal", "Chiffre Rouge"],
  },
  {
    name: "Franck Muller",
    officialName: "Franck Muller",
    slug: "franck-muller",
    image: "/iconic-watches/franck-muller.webp",
    iconicModel: "Cintrée Curvex Crazy Hours",
    officialUrl: "https://www.franckmuller.com/mens-collection",
    models: ["Crazy Hours", "Cintrée Curvex", "Curvex CX", "Vanguard", "Long Island", "Master Square", "Round", "Skafander", "Galet", "Grand Complications"],
  },
  {
    name: "Glashütte",
    officialName: "Glashütte Original",
    slug: "glashutte",
    image: "/iconic-watches/glashutte.webp",
    iconicModel: "PanoMaticLunar",
    officialUrl: "https://www.glashuette-original.com/en/collection/",
    models: ["Pano", "Senator", "Spezialist", "Vintage", "Serenade"],
  },
  {
    name: "Grand Seiko",
    officialName: "Grand Seiko",
    slug: "grand-seiko",
    image: "/iconic-watches/grand-seiko.webp",
    iconicModel: "Heritage “Snowflake” SBGA211",
    officialUrl: "https://www.grand-seiko.com/us-en/collections/all",
    models: ["Masterpiece Collection", "Evolution 9 Collection", "Heritage Collection", "Sport Collection", "Elegance Collection"],
  },
  {
    name: "Hublot",
    officialName: "Hublot",
    slug: "hublot",
    image: "/iconic-watches/hublot.webp",
    iconicModel: "Big Bang Unico",
    officialUrl: "https://www.hublot.com/en-us/watches",
    models: ["Big Bang Original", "Big Bang Unico", "Spirit of Big Bang", "Square Bang Unico", "Classic Fusion", "Exceptional Timepieces"],
  },
  {
    name: "IWC",
    officialName: "IWC Schaffhausen",
    slug: "iwc",
    image: "/iconic-watches/iwc.webp",
    iconicModel: "Big Pilot’s Watch 43",
    officialUrl: "https://www.iwc.com/us-en",
    models: ["Pilot’s Watches", "Portugieser", "Portofino", "Ingenieur", "Aquatimer"],
  },
  {
    name: "Jaeger LeCoultre",
    officialName: "Jaeger-LeCoultre",
    slug: "jaeger-lecoultre",
    image: "/iconic-watches/jaeger-lecoultre.webp",
    iconicModel: "Reverso Tribute Monoface",
    officialUrl: "https://www.jaeger-lecoultre.com/us-en/watches",
    models: ["Reverso", "Master Control", "Master Ultra Thin", "Master Grande Tradition", "Rendez-Vous", "Polaris", "Duometre", "Calibre 101", "Hybris Mechanica"],
  },
  {
    name: "Longines",
    officialName: "Longines",
    slug: "longines",
    image: "/iconic-watches/longines.webp",
    iconicModel: "Longines Legend Diver",
    officialUrl: "https://www.longines.com/en-us/watches",
    models: ["Conquest", "HydroConquest", "Longines Spirit", "Spirit Zulu Time", "Longines Master Collection", "Longines Legend Diver", "Ultra-Chron", "Longines DolceVita", "Mini DolceVita", "La Grande Classique de Longines", "Flagship Heritage", "Conquest Heritage", "Heritage Classic", "Longines PrimaLuna", "Evidenza", "Record", "Longines Elegant Collection"],
  },
  {
    name: "MB&F",
    officialName: "MB&F",
    slug: "mb-and-f",
    image: "/iconic-watches/mbf.webp",
    iconicModel: "Legacy Machine Perpetual",
    officialUrl: "https://www.mbandf.com/machines",
    models: ["Legacy Machines", "Horological Machines", "Special Projects", "Performance Art", "M.A.D.Editions"],
  },
  {
    name: "Panerai",
    officialName: "Panerai",
    slug: "panerai",
    image: "/iconic-watches/panerai.webp",
    iconicModel: "Luminor Marina",
    officialUrl: "https://www.panerai.com/us/en/collections/watch-collection.html",
    models: ["Luminor", "Luminor Marina", "Luminor Due", "Radiomir", "Submersible", "Luna Rossa"],
  },
  {
    name: "Patek Philippe",
    officialName: "Patek Philippe",
    slug: "patek-philippe",
    image: "/iconic-watches/patek-philippe.webp",
    iconicModel: "Nautilus 5811/1G",
    officialUrl: "https://www.patek.com/en/collection",
    models: ["Grand Complications", "Complications", "Calatrava", "Nautilus", "Aquanaut", "Cubitus", "Gondolo", "Golden Ellipse", "Twenty~4"],
  },
  {
    name: "R0lex",
    officialName: "Rolex",
    slug: "r0lex",
    image: "/iconic-watches/rolex.webp",
    iconicModel: "Submariner Date",
    officialUrl: "https://www.rolex.com/en-us/watches/find-rolex",
    models: ["Air-King", "Cosmograph Daytona", "Datejust", "Lady-Datejust", "Day-Date", "Deepsea", "Explorer", "Explorer II", "GMT-Master II", "Oyster Perpetual", "Sea-Dweller", "Sky-Dweller", "Submariner", "Yacht-Master", "1908", "Land-Dweller"],
  },
  {
    name: "Richard Mille",
    officialName: "Richard Mille",
    slug: "richard-mille",
    image: "/iconic-watches/richard-mille.webp",
    iconicModel: "RM 35-03 Rafael Nadal",
    officialUrl: "https://www.richardmille.com/collections",
    models: ["RM HJ-02", "RM 75-01", "RM UP-01 Ferrari", "RM 74-02", "RM 74-01", "RM 72-01", "RM 67-02", "RM 67-01", "RM 66", "RM 65-01", "RM 64-01", "RM 63-02", "RM 55-01", "RM 43-01", "RM 41-01", "RM 037", "RM 35-03", "RM 33-03", "RM 30-01", "RM 17-01", "RM 07-04", "RM 07-01"],
  },
  {
    name: "Seiko",
    officialName: "Seiko",
    slug: "seiko",
    image: "/iconic-watches/seiko.webp",
    iconicModel: "Prospex 1965 Heritage Diver",
    officialUrl: "https://www.seikowatches.com/us-en/products",
    models: ["King Seiko", "Prospex", "Presage", "Astron", "5 Sports", "Seiko Power Design Project", "Coutura", "Diamond Collection"],
  },
  {
    name: "Tag Heuer",
    officialName: "TAG Heuer",
    slug: "tag-heuer",
    image: "/iconic-watches/tag-heuer.webp",
    iconicModel: "Monaco Chronograph",
    officialUrl: "https://www.tagheuer.com/us/en/timepieces/collections/",
    models: ["TAG Heuer Carrera", "TAG Heuer Formula 1", "TAG Heuer Aquaracer", "TAG Heuer Connected", "TAG Heuer Monaco", "TAG Heuer Link"],
  },
  {
    name: "Tudor",
    officialName: "TUDOR",
    slug: "tudor",
    image: "/iconic-watches/tudor.webp",
    iconicModel: "Black Bay 58",
    officialUrl: "https://www.tudorwatch.com/en/watch-family",
    models: ["TUDOR Monarch", "Black Bay", "Black Bay 54", "Black Bay 58", "Black Bay 68", "Black Bay One", "Black Bay Pro", "Black Bay Chrono", "Black Bay GMT", "Pelagos", "Pelagos FXD", "TUDOR Royal", "Clair de Rose", "Ranger", "Black Bay Bronze", "1926"],
  },
  {
    name: "Vacheron Constantin",
    officialName: "Vacheron Constantin",
    slug: "vacheron-constantin",
    image: "/iconic-watches/vacheron-constantin.webp",
    iconicModel: "Overseas Self-Winding",
    officialUrl: "https://www.vacheron-constantin.com/us/en/watches/all-collections.html",
    models: ["Overseas", "Historiques", "Traditionnelle", "Fiftysix", "Patrimony", "Égérie", "Métiers d’Art", "Heures Créatives", "Malte"],
  },
];

export const CATALOG_MODEL_LINE_COUNT = CATALOG_BRANDS.reduce((total, brand) => total + brand.models.length, 0);

export function getCatalogBrand(slug: string) {
  return CATALOG_BRANDS.find(brand => brand.slug === slug);
}
